name: airplane_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^5.0.1
  google_fonts: ^3.0.1
  flutter_native_splash: ^2.2.8
  responsive_framework: ^0.2.0
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.1
  cloud_firestore: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#5C40CC"

  image: assets/icon_plane.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_plane.png"
