// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGIuoW33CaKrNrDdFnXQwkJc5j2hhqs0Y',
    appId: '1:255946375029:web:293ace9f891c0d8015dd3c',
    messagingSenderId: '255946375029',
    projectId: 'airplane-bb6f1',
    authDomain: 'airplane-bb6f1.firebaseapp.com',
    storageBucket: 'airplane-bb6f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJA1k3VHI29_T_asukSHEBLJVgRi-jxyI',
    appId: '1:255946375029:android:35fa763923fe87fe15dd3c',
    messagingSenderId: '255946375029',
    projectId: 'airplane-bb6f1',
    storageBucket: 'airplane-bb6f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyY4W8W5Ye4kkzHRMO8TDR01J5SsZj3tM',
    appId: '1:255946375029:ios:186747549d64b63015dd3c',
    messagingSenderId: '255946375029',
    projectId: 'airplane-bb6f1',
    storageBucket: 'airplane-bb6f1.appspot.com',
    iosClientId: '255946375029-m2futih72nvnjg8kue24rq6t0t1ruheu.apps.googleusercontent.com',
    iosBundleId: 'com.example.airplaneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyY4W8W5Ye4kkzHRMO8TDR01J5SsZj3tM',
    appId: '1:255946375029:ios:7d9571d7e01ed5fd15dd3c',
    messagingSenderId: '255946375029',
    projectId: 'airplane-bb6f1',
    storageBucket: 'airplane-bb6f1.appspot.com',
    iosClientId: '255946375029-n1f0l2s6tnpkmq66pc5h03ftmqm7tors.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
